version: '3'

services:
  server1:
    container_name: server1
    build: ./springboot
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      serverNetwork:
        aliases:
            - server1
  server2:
    container_name: server2
    build: ./springboot
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      serverNetwork:
        aliases:
            - server2

networks:
  serverNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24